version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:ikeali123@db:5432/llm  
      REDIS_URL: redis://redis:6379 
    depends_on:
      - db
      - redis  

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ikeali123
      POSTGRES_DB: llm
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"  # Official Redis image
    ports:
      - "6379:6379"  

volumes:
  pgdata:
