apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-benchmark-llm_benchmark
  labels:
    helm.sh/chart: llm_benchmark-0.1.0
    app.kubernetes.io/name: llm_benchmark
    app.kubernetes.io/instance: llm-benchmark
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: llm_benchmark
  template:
    metadata:
      labels:
        app.kubernetes.io/name: llm_benchmark
        app.kubernetes.io/instance: llm-benchmark
    spec:
      serviceAccountName: llm-benchmark-llm_benchmark
      containers:
        - name: llm_benchmark  # Ensure name is lowercase
          image: "nginx:"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: EXAMPLE_ENV
              value: "value"