{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "llm_benchmark.serviceAccountName" . | lower }}
  labels:
    helm.sh/chart: llm_benchmark-0.1.0
    app.kubernetes.io/name: llm_benchmark
    app.kubernetes.io/instance: llm-benchmark
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}